### ISSUE TITLE
Modify rescue and modify rat API endpoint is broken

### ISSUE THREAD

**Issue by xlexi** [FuelRats/api.fuelrats.com#28]
The PUT /api/rescues/{id} endpoint for modifying an existing rescue appears to be broken, when supplied with a valid id. i.e "/api/rescues/56a78141f9fbac397a27ab3e" the following error is received.
```
>> TypeError: Invalid `path`. Must be either string or array
>>     at Object.exports.get (/Users/alex/api.fuelrats.com/node_modules/mongoose/node_modules/mpath/lib/index.js:43:11)
>>     at Object.exports.getValue (/Users/alex/api.fuelrats.com/node_modules/mongoose/lib/utils.js:588:16)
>>     at model.Document.getValue (/Users/alex/api.fuelrats.com/node_modules/mongoose/lib/document.js:781:16)
>>     at model.Model.$__version (/Users/alex/api.fuelrats.com/node_modules/mongoose/lib/model.js:594:23)
>>     at model.Model.$__delta (/Users/alex/api.fuelrats.com/node_modules/mongoose/lib/model.js:509:10)
>>     at model.Model.$__handleSave (/Users/alex/api.fuelrats.com/node_modules/mongoose/lib/model.js:151:22)
>>     at model.Model.$__save (/Users/alex/api.fuelrats.com/node_modules/mongoose/lib/model.js:189:9)
>>     at /Users/alex/api.fuelrats.com/node_modules/mongoose/lib/model.js:288:11
>>     at new Promise.ES6 (/Users/alex/api.fuelrats.com/node_modules/mongoose/lib/promise.js:45:3)
>>     at model.Model.save (/Users/alex/api.fuelrats.com/node_modules/mongoose/lib/model.js:287:10)
>>     at model._done (/Users/alex/api.fuelrats.com/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:101:24)
>>     at _next (/Users/alex/api.fuelrats.com/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:64:28)
>>     at fnWrapper (/Users/alex/api.fuelrats.com/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:186:18)
>>     at model.<anonymous> (/Users/alex/api.fuelrats.com/api/models/rescue.js:98:3)
>>     at _next (/Users/alex/api.fuelrats.com/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:62:30)
>>     at fnWrapper (/Users/alex/api.fuelrats.com/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:186:18)
>>     at model.Object.defineProperty.value.fn (/Users/alex/api.fuelrats.com/node_modules/mongoose/lib/schema.js:250:9)
>>     at _next (/Users/alex/api.fuelrats.com/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:62:30)
>>     at fnWrapper (/Users/alex/api.fuelrats.com/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:186:18)
>>     at /Users/alex/api.fuelrats.com/node_modules/mongoose/lib/schema.js:234:13
>>     at complete (/Users/alex/api.fuelrats.com/node_modules/mongoose/lib/document.js:1149:5)
>>     at /Users/alex/api.fuelrats.com/node_modules/mongoose/lib/document.js:1175:20
[ERROR] 13:33:31 TypeError
```

**Comment by tyrope** [comment]
Not sure if [the dev server](http://dev.api.fuelrats.com/api/rescues/56a838e900b8918008fd0523) is up to date, but it works there. So if it's not, git blame between the two versions? :)
```
{
    "links": 
{
    "self": "/api/rescues/56a838e900b8918008fd0523"
},
"data": 
{
    "_id": "56a838e900b8918008fd0523",
    "createdAt": ​1450501200000,
    "lastModified": ​1453865248021,
    "notes": "",
    "successful": true,
    "system": "ALRAI SECTOR JH-V B2-4",
    "tempRats": [ ],
    "rats": 
        [
            "56a838e200b8918008fce982"
        ],
        "quotes": [ ],
        "platform": "pc",
        "open": false,
        "epic": false,
        "codeRed": false,
        "archive": true,
        "active": false,
        "id": "56a838e900b8918008fd0523"
    }
}
```
