### ISSUE TITLE
Cannot find module 'swagger-mongoose'

### ISSUE THREAD

**Issue by tyrope** [FuelRats/api.fuelrats.com#8]
Running `npm run dev` on 237ce5bcef4ddf81c3004667bd49930f74925c5a (Current master)

```
Error: Cannot find module 'swagger-mongoose'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/tyrope/fuelRatsAPI/controllers/rescue.js:4:19)
    at Module._compile (module.js:456:26)
    at Module._extensions..js (module.js:474:10)
    at Object.nodeDevHook [as .js] (/home/tyrope/fuelRatsAPI/node_modules/node-dev/lib/hook.js:43:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/tyrope/fuelRatsAPI/api.js:25:10)
    at Module._compile (module.js:456:26)
    at Module._extensions..js (module.js:474:10)
    at Object.nodeDevHook [as .js] (/home/tyrope/fuelRatsAPI/node_modules/node-dev/lib/hook.js:43:7)
```

**Comment by tyrope** [comment]
Temporary workaround: manually `npm install swagger-mongoose`

**Comment by trezy** [comment]
This will be fixed once I merge the UGRADZ branch. ;-)
